use_frameworks!

platform :ios, '9.0'

target 'JKDataHelper_Swift_Example' do
  pod 'JKDataHelper_Swift', :path => '../../'

  target 'JKDataHelper_Swift_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
